language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer self-update
  - composer install --dev

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - composer show yiisoft/yii2
  - phpunit --version
  - phpunit --coverage-text --coverage-clover=coverage.clover
